vich_uploader:
    db_driver: orm

    metadata:
        type: attribute

    mappings:
        project_image:
            uri_prefix: /assets/images/project
            upload_destination: '%kernel.project_dir%/public/assets/images/project'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
